name: Daily Chatbot Evaluation

on:
  schedule:
    # 2AM Pacific = 9AM UTC (PST is UTC-8, PDT is UTC-7; GitHub uses UTC)
    - cron: '0 9 * * *'
  workflow_dispatch:
  
jobs:
  evaluate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies with uv
        run: uv pip install --system .

      - name: Run evaluation
        env:
          DEEPEVAL_API_KEY: ${{ secrets.DEEPEVAL_API_KEY }}
          KUSTOMER_API_KEY: ${{ secrets.KUSTOMER_API_KEY }}
          KUSTOMER_ASSIGNED_USER_ID: ${{ secrets.KUSTOMER_ASSIGNED_USER_ID }}
          KUSTOMER_QUEUE_ID: ${{ secrets.KUSTOMER_QUEUE_ID }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          GOOGLE_DRIVE_CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
        run: |
          python -m evaluator_service

      - name: Debug env
        run: echo "KUSTOMER_API_KEY=$KUSTOMER_API_KEY"
        env:
          KUSTOMER_API_KEY: ${{ secrets.KUSTOMER_API_KEY }}
